#!/usr/bin/env python3 

from config import * 


if __name__ == "__main__":
    import sys 
    
    app = QApplication(sys.argv)
    MainWindow = Main()
    
    MainWindow.show()
    sys.exit(app.exec())


